# docker-compose.yaml
version: "3"
services:
  server:
    build: .
    container_name: <%= name %>_server-dev
    command: npm start
    ports:
    - 8081:8081
    - 3001:3001
    volumes:
    - .:/app:rw
    - /app/node_modules
