#!/usr/bin/env bash
# MIT © Sindre Sorhus - sindresorhus.com
# using fork as starting point: https://gist.github.com/ernscht/731f9ec710e5b3d01fa3

# git hook to run a command after `git pull` if a specified file was changed
# Run `chmod +x post-merge` to make it executable then put it into `.git/hooks/`.

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_run() {
	echo "$changed_files" | grep -E --quiet "$1" && eval "$2"
}

# `npm install` and `npm prune` if `package.json` gets changed
check_run package.json "npm install && npm prune"

# `bower install` and `bower prune` if `bower.json` gets changed
check_run bower.json "bower install && bower prune"

# `sync hooks` if `.githooks` gets changed
check_run ".githooks" "npm run githooks"
